// Writes contract ABIs and known deployments into the app as typed TypeScript.
// Usage: npm run export-abis
const fs = require("fs");
const path = require("path");

const ARTIFACTS = path.join(__dirname, "..", "artifacts", "src");
const OUT_DIR = path.join(__dirname, "..", "..", "app", "src", "generated");
const CONTRACTS = {
  laneRouterAbi: "LaneRouter.sol/LaneRouter.json",
  laneTokenAbi: "mocks/LaneToken.sol/LaneToken.json",
  drawdownRetireAbi: "DrawdownRetire.sol/DrawdownRetire.json",
  feeRouterAbi: "FeeRouter.sol/FeeRouter.json",
  laneOracleAbi: "LaneOracle.sol/LaneOracle.json",
};

fs.mkdirSync(OUT_DIR, { recursive: true });

let abis = "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n";
for (const [name, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, file), "utf8"));
  abis += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
fs.writeFileSync(path.join(OUT_DIR, "abis.ts"), abis);

const deployments = {};
const dir = path.join(__dirname, "..", "deployments");
if (fs.existsSync(dir)) {
  for (const f of fs.readdirSync(dir).filter((f) => f === "robinhood.json" || f === "localhost.json")) {
    const d = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    if (d.network === "hardhat") continue;
    deployments[d.chainId] = d;
  }
}
fs.writeFileSync(
  path.join(OUT_DIR, "deployments.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n" +
    `export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n\n` +
    `export type Deployment = {
  network: string;
  chainId: number;
  usdg: \`0x\${string}\`;
  laneToken: \`0x\${string}\` | null;
  deployer: \`0x\${string}\`;
  timelock: \`0x\${string}\`;
  roles: { admin: \`0x\${string}\`; guardian: \`0x\${string}\`; keeper: \`0x\${string}\` };
  oracle: \`0x\${string}\`;
  router: \`0x\${string}\`;
  adapter: \`0x\${string}\`;
  feeRouter: \`0x\${string}\`;
  drawdownRetire: \`0x\${string}\`;
  poolManager: \`0x\${string}\`;
  v3Factory: \`0x\${string}\`;
  ponsHook: \`0x\${string}\`;
  stocks: Record<string, { address: \`0x\${string}\`; name: string; feed: \`0x\${string}\` }>;
  [key: string]: unknown;
};\n`
);
const config = require("../config/robinhood.json");
const catalog = {
  chainId: config.network.chainId,
  explorer: config.network.explorer,
  usdg: config.tokens.usdg.address,
  stocks: Object.fromEntries(Object.entries(config.equityTokens).map(([t, v]) => [t, { name: v.name, address: v.address }])),
  uniswap: {
    v3Fees: config.uniswap.v3Fees,
    v4HooklessPools: config.uniswap.v4HooklessPools,
    ethUsdgPool: config.uniswap.ethUsdgPool,
  },
  pons: config.pons,
  routerFeeBps: config.launch.routerFeeBps,
  maxOracleDeviationBps: config.launch.maxOracleDeviationBps,
};
fs.writeFileSync(
  path.join(OUT_DIR, "catalog.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n" +
    `export const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`
);

console.log(`Exported ${Object.keys(CONTRACTS).length} ABIs and ${Object.keys(deployments).length} deployment(s) to ${OUT_DIR}`);
